version: '3.4'

services:
  api:
    build:
      context: ./api
      network: host
      dockerfile: Dockerfile.dev
      args:
        PORT: 3015
        CLIENT_URL: ${CLIENT_URL}
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: ${DATABASE_URL}
    container_name: gga-api
    ports: 
      - '3015:3015'
    networks:
      - web
    volumes:
      - 'api_node_modules:/app/node_modules'
      - './api:/app'
    restart: always
  client:
    build:
      context: ./client
      network: host
      dockerfile: Dockerfile.dev
      args:
        VITE_PORT: ${VITE_PORT}
        VITE_API_URL: ${VITE_API_URL}
    container_name: gga-client
    volumes:
      - 'client_node_modules:/app/node_modules'
      - './client:/app'
    networks:
      - web
    ports:
      - '5000:3000'
    depends_on:
      - api
    restart: always

volumes:
  mongo-data:
  api_node_modules:
  client_node_modules:

networks:
  web: