FROM node:16.18.0

LABEL version="0.0.1"
LABEL description="Greek Gods Arena API"
LABEL maintainer = ["sadaouiwalid@gmail.com"]

ENV NODE_ENV=development

WORKDIR /app

COPY ./package.json package.json
COPY ./package-lock.json package-lock.json
RUN npm install
COPY . /app
RUN ls -l

EXPOSE 3000

CMD ["npm", "run", "dev"]